### ISSUE TITLE
Oszoliné Somogyi Ildikó képe

### ISSUE THREAD

**Issue by parphis** [ighcsakvar/esterhazyiskola#59]
@ighcsakvar Ibolya, Péter, kérlek töltsétek fel ide az ő képét, mert nem találom. Köszi!

**Comment by ighcsakvar** [comment]
Szia István!Bemásoltam a képet. Az Assignees-nél bejelöltelek téged. Remélem, így megfelelő lesz.Péter Küldte a Windows 10 Posta Feladó: Istvan VigElküldve: 2021. január 21., csütörtök 21:52Címzett: ighcsakvar/esterhazyiskolaMásolatot kap: Esterhazy Iskola; AssignTárgy: [ighcsakvar/esterhazyiskola] Oszoliné Somogyi Ildikó képe (#59) @ighcsakvar Ibolya, Péter, kérlek töltsétek fel ide az ő képét, mert nem találom. Köszi!—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ighcsakvar** [comment]
![CSIT9414_rg0](https://user-images.githubusercontent.com/77481626/105483868-c557e680-5caa-11eb-9c36-d696fd7ab87e.jpg)

**Comment by parphis** [comment]
Köszönöm, teljesen jó fel is töltöttem :)
